name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "release" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: 👻 Checkout Source Code 👻
      uses: actions/checkout@v2

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app


    - name: Decode GoogleService-Info.plist
      run: |
        echo "$GOOGLESERVICE_INFO" | base64 --decode > ./HowManySet/Resources/GoogleService-Info.plist
      env:
          GOOGLESERVICE_INFO: ${{ secrets.GOOGLESERVICE_INFO }}
    - name: 📱 List Available Simulators
      run: xcrun simctl list devices

    - name: 🛠 Start xcode build
      run: |
        xcodebuild clean test \
          -project HowManySet.xcodeproj \
          -scheme HowManySet \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4' \
          -only-testing:HowManySetTests
