name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "release" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Start xcode build 🛠
      run: |
        xcodebuild clean test \
          -project HowManySet\HowManySet.xcodeproj \
          -scheme HowManySet \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
          -only-testing:HowManySetTests
